services:
  postgres:
    image: postgres:17-alpine
    container_name: myrecipebook_db
    environment:
      POSTGRES_DB: myrecipebook_db
      POSTGRES_USER: myrecipebook
      POSTGRES_PASSWORD: myrecipebook@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data: